components/customers/CustomerPage.tsx
components/customers/infoTabs/CustomerDetails.tsx
components/staff/StaffForm.tsx

Improved Customers

---

app/(dashboard)/manage/staff/page.tsx

[Test] Test

---

components/calendar/header/actions/calendar-header-actions-mode.tsx

- Changed Day, Week, Month view buttons 
- Deleted the AnimatePresence from the buttons
---
- Made this change so Users can always see where to find the different views. Before it was confusing where to initially find them
---
---
---
- https://trello.com/c/PG1DSfGa/174-change-the-buttons-on-calendar-to-say-day-week-month
---
- There will be lots of formatting changes on the code

[Chore] Changed Calendar header buttons 

---

components/customers/CustomerPage.tsx
components/locations/LocationPage.tsx
components/memberships/MembershipPage.tsx
components/staff/StaffPage.tsx
components/staff/StaffTable.tsx
components/staff/columnsStaff.tsx

- Added columnsStaff component
- Changed StaffTable component
- Changed staffPage component
- Edited other pages so drop down says filters instead of columns 
---
- Added columnsStaff: Centralized all column definitions (IDs, headers, and cell renderers) into one file so that the Filters dropdown can iterate over them and toggle visibility consistently, reducing duplication and making it easy to add or remove columns.
- Updated StaffTable: Modified the component to conditionally render each column based on columnVisibility, while retaining sorting, pagination, and row action logic, ensuring the table adapts dynamically without breaking existing functionality.
- Updated StaffPage: Introduced a Filters dropdown that updates columnVisibility state for showing or hiding specific columns, and …

[Feature] Added filters to Staff Page

---

components/calendar/CalendarPage.tsx
components/calendar/Filter.tsx

- Moved the location of filters
- Added button for apply filters
- Fixed date range filter
---
- Moved the location so the Calendar is always the same size unless sidebar is open / closed
- Added a button for apply filters to close the right drawer once a user has completed filtering
- Fixed the date range filter, I found a bug that when you click on a certain day it would select the day before, so changed how we are reading the date and fixed what day is being selected
---
---
---
- https://trello.com/c/Zhujbqde/173-relocate-filters
---

[Chore] Moved Filters on Calendar, bug fix for the filters

---

services/haircuts.ts

- Added filter on the GET request
---
- Added this change so the GET request doesn't pick up our folder for the images and display a broken image
---
---
- Before
- After
---
- https://trello.com/c/v1s3D9Uk/180-delete-haircut-1-folder-from-haircut-portfolio
---

[Chore] Fix haircut portfolio page

---

components/memberships/infoTabs/plans/Plans.tsx

- Deleted background colors 
---
- Deleted the bg line so it defaults to the light or dark theme, added light / dark themed hover to be consistent with the rest of the website 
---
---
---
- https://trello.com/c/H5unKGh6/177-fix-membership-plans-styling
---

[Chore] Fixed Membership Styles background color

---

components/calendar/CalendarPage.tsx
services/events.ts

- Added get request in services
- Added get color for program type
---
- Added new service so we can dynamically get the events each month
- Added get color for program type so each program will keep the same color styling from before
---
---
- https://trello.com/c/o8sKz4iT/186-fix-events-api-to-display-more-than-20-events
---

[Feature] Added getEventsbyMonth

---

components/Barbershop/AppointmentInfoPanel.tsx
components/Barbershop/BarberPage.tsx
components/customers/CustomerTable.tsx
components/locations/LocationPage.tsx
components/locations/infoTabs/Details.tsx
components/locations/table/LocationTable.tsx
components/locations/table/columns.tsx
components/memberships/MembershipPage.tsx
components/memberships/infoTabs/Details.tsx
components/memberships/table/MembershipTable.tsx
components/memberships/table/columns.tsx
components/programs/ProgramInfoPanel.tsx
components/programs/ProgramPage.tsx
components/programs/table/ProgramTable.tsx
components/programs/table/columns.tsx
components/staff/StaffForm.tsx
components/staff/StaffPage.tsx
components/staff/StaffTable.tsx
components/staff/columnsStaff.tsx
services/staff.ts

- Deleted Select options from customer table
- Removed delete button from column actions
- Added confirmation before deleting on info panel drawer
- Took out select options from location table
- Added delete functionality to locations
- Styled delete button in info panel
- Added header to program actions button
- Took out membership select buttons
- Added confirmation before delete membership
- Styled membership delete button 
- Took out delete action from membership table
- Add delete staff to Staff form
- Styled delete staff button
- Remove select buttons from table
- Added Delete service for staff
- Styled delete button on barber page
- Delete toast notification on barber page that says appointment added after deleting it 
---
- Deleted select options so there is now only one way to …

[Feature] Fixed delete functionality on all pages

---

components/memberships/infoTabs/plans/Plans.tsx

- Delete background color on adding plan
---
- Deleted the background color so the background follows the light and dark mode
---
---
---
- https://trello.com/c/MNcdNKbW/192-fix-add-membership-plan-styling
---

[Chore] Fix Add Membership Plan Styling

---

components/app-sidebar.tsx
components/nav-main.tsx
components/ui/sidebar.tsx

- Removed dropdowns
- Added icons to each link
- Increased text size
- Added margin around Links
---
- Removed dropdowns so all Links are always visible
- Added icons for a clean user experience, they will be present when the sidebar is closed so you can always click to different pages
- Increased text size for easy to read Links
- Added some margin around each Link so they were not crowded 
---
---
---
https://trello.com/c/aXq63xw0/183-restyle-sidebar
---

[Chore] Restyle sidebar 

---

components/Barbershop/BarberPage.tsx

- Added state for Active Barbers and Drawer Visibility
- Added handler to Fetch Active Barbers
- Added interactive “Active Barbers” Card
- Added drawer Showing Active Barbers
---
- Added activeBarbers and barberDrawerOpen to track fetched barber data and manage the new drawer’s visibility
- Created handleActiveBarbersClick, which calls getAllStaffs for barbers, filters the active ones, stores them in state, and opens the drawer. Errors trigger a toast message
- Converted the “Active Barbers” stat card into a clickable element. Clicking invokes handleActiveBarbersClick and opens the drawer to show the fetched list
- Inserted a RightDrawer that displays the active barbers’ names in a styled list, with a header and rounded muted items for clarity
---
---
---
- …

[Feature] Added Active barbers list

---

actions/serverActions.ts
app/(dashboard)/manage/games/page.tsx
components/app-sidebar.tsx
components/games/AddGameForm.tsx
components/games/GameInfoPanel.tsx
components/games/GamesPage.tsx
components/games/table/GameTable.tsx
components/games/table/columns.tsx
services/games.ts

- Added to server actions
- Created Games page
- Added to sidebar 
- Created Addgame form
- Created Game info panel
- Created Games page component
- Created columns
- Added to games service 
---
- Added to server actions – Provided revalidateGames() so the new games page can be revalidated when games are created, updated, or deleted
- Created Games page – Implemented page.tsx under /manage/games to fetch games client‑side and display them for users
- Added to sidebar – Inserted a “Games” link in AppSidebar so admins can navigate to the new management page
- Created AddGameform – Built AddGameForm to let admins input teams, location, times, and status when creating a game
- Created Game info panel – Added GameInfoPanel to edit or delete a selected game with the same fields as the add form …

[Feature] Created Games page with all backend functionality 

---

actions/serverActions.ts
app/(dashboard)/manage/practices/page.tsx
components/app-sidebar.tsx
components/practices/AddPracticeForm.tsx
components/practices/PracticeInfoPanel.tsx
components/practices/PracticesPage.tsx
components/practices/table/PracticeTable.tsx
components/practices/table/columns.tsx
services/practices.ts
types/practice.ts

- Changed server actions
- Added Practice Page
- Changed app sidebar
- Added Add practice form 
- Added Practice info panel
- Added Practices Page component 
- Added Practice Table
- Added columns 
- Added practices type
- Added practices service 
---
- Changed server actions – A revalidatePractices function was added so practice changes refresh the /manage/practices page when server actions run
- Added Practice Page – Created an admin-only page that fetches and displays all practices in a loading skeleton and drawer layout
- Changed app sidebar – Inserted a “Practices” link so users can reach the new management page from the sidebar menu
- Added Add practice form – Implemented a form supporting one-time and recurring practice creation with dropdown data loading and validation
- Added …

[Feature] Added Practice Page for Users 

---

app/api/docs/swagger.json

- Updated swagger json file
---
- Update the file to have the recent endpoints 
---

[Chore] Update swagger file

---

app/api/docs/swagger.json
components/calendar/CalendarPage.tsx
components/programs/ProgramPage.tsx
components/programs/infoTabs/Details.tsx
components/programs/table/columns.tsx

- Changed calendar page
- Changed Program page
- Changed details file
- Changed columns file
---
- Changed calendar page - The calendar’s color-selection helper was extended with new cases for “tournament,” “tryouts,” and “event,” ensuring that events of these types render with appropriate colors
- Changed Program page - The page now recognizes the new program types in its type union and filter logic, counting and filtering programs for “tournament,” “tryouts,” “event,” and “other”
- Changed details file - The dropdown in the Details form was updated so users can choose from the new program types when creating or editing a program
- Changed columns file - The table’s badge color mapping adds cases for the new program types, allowing each type to display with a consistent color in program …

[Chore] Fix Programs page so it shows correct types, filters, colors

---

components/Barbershop/AddAppointmentForm.tsx
components/Barbershop/AppointmentInfoPanel.tsx
components/Barbershop/Appointments.tsx
components/Barbershop/BarberTable.tsx
components/Playground/AddBookingForm.tsx
components/Playground/BookingInfoPanel.tsx
components/Playground/PlaygroundPage.tsx
components/Playground/PlaygroundTable.tsx
components/calendar/CalendarPage.tsx
components/calendar/event/AddEventForm.tsx
components/calendar/event/EditEventForm.tsx
components/games/AddGameForm.tsx
components/games/GameInfoPanel.tsx
components/games/table/columns.tsx
components/practices/AddPracticeForm.tsx
components/practices/PracticeInfoPanel.tsx
components/practices/table/columns.tsx
lib/utils.ts
services/playground.ts

- Changed barbershop appointment form
- Changed barbershop info panel
- Changed barbershop appointment 
- Changed barbershop barber table
- Changed playground add booking form
- Changed playground booking info panel
- Changed playground page component 
- Changed playground table
- Changed games add game form
- Changed game info panel
- Changed games columns
- Changed practice add practice form
- Changed practice info panel
- Changed practice columns
- Changed utils.ts
- Changed playground service 
- Changed calendar page component 
- Changed calendar add event form
- Changed calendar edit event form
---
- The barbershop appointment form now serializes start and end times with toZonedISOString so submitted appointments retain the user’s local time without timezone shifts
- The barbershop …

[Chore] Added a Time Zone helper function that will adjust the time to local time for booking / adding events, practices, games etc.

---

app/(dashboard)/manage/games/page.tsx
app/(dashboard)/manage/practices/page.tsx
app/(dashboard)/manage/teams/page.tsx
components/app-sidebar.tsx

- Added Coaches to Teams, Games and Practices pages
- Added Coaches to sidebar links 
---
- Added coach role to the pages so they can access them 
- Added links to their roles so they can see what pages they can access and manage 
---
---
- https://trello.com/c/H7Z72xB8/278-fix-roles-for-coach
---

[Feature] Assigned Coach roles to Pages and Sidebar 

---

components/calendar/event/AddEventForm.tsx
components/calendar/event/EditEventForm.tsx
components/programs/infoTabs/ScheduleCard.tsx
lib/dates.ts

- changed add event form
- changed schedule card
---
- Changed add event form: The form now formats start, end, and recurring times with formatEventDate, ensuring events are submitted in America/Edmonton time instead of UTC.
- Changed schedule card: Each session’s start and end times now use the same timezone-aware formatter, preventing a six-hour shift when displaying program schedules.
---
---
- https://trello.com/c/p8lfSQXB/273-fix-reoccurring-events
---

[Bugfix] Edited more files to try to fix the time change bug

---

components/customers/CustomerPage.tsx
components/customers/CustomersManager.tsx

- Changed customer page
- Changed customer manager 
---
- Changed customer page: This update keeps the search box and visible customer list in sync with incoming data so results appear immediately without needing a page refresh.
- Changed customer manager: We now refresh the active and archived customer arrays when new props arrive, ensuring both lists reflect the latest search results and archiving actions.
---
---
- https://trello.com/c/hxjxBWKp/283-fix-customers-page-search
---

[Chore] Fix customer search

---

app/(dashboard)/page.tsx

- Updated dashboard page 
---
- This update was needed so the dashboard displays the actual number of active members by fetching the total from the customer service rather than relying on a hard-coded value
---
---
- https://trello.com/c/lrbYHGIq/291-active-member-count-for-dashboard
---

[Chore] Updated active customers on dashboard so it uses GET customers api 

---

components/calendar/Filter.tsx

- Changed filter component 
---
- The filter component was changed to remove the nonfunctional trainer filter, simplifying the calendar view.
---
---
- https://trello.com/c/srOQu05i/282-fix-trainers-filter-on-calendar-page
---

[Chore] Removed Trainer Filter

---

app/(dashboard)/manage/games/page.tsx
app/api/Api.ts
app/api/docs/swagger.json
components/games/AddGameForm.tsx
components/games/GameInfoPanel.tsx
components/games/GamesPage.tsx
services/games.ts
types/games.ts

- Updated swagger file 
- Changed api
- Changed add game form
- Changed game info panel
- Changed game service
- Changed game type
-----
- Changed games page
- Changed add game form
- Changed game info panel
- Changed games page component
---
- Updated swagger file - We did this so we could have the updated endpoints for assigning a court to a game 
- Changed API - Needed to accept and return an optional courtId/courtName for games so backend calls could persist court selections.
- Changed Add Game Form - Required an optional court dropdown and location-based court filtering so users can assign a court during game creation.
- Changed Game Info Panel - Needed to show and allow editing of a game's court assignment, mirroring the behavior already present for practices.
- Changed Game Service …

[Chore] Add optional court to games / Auto refresh after CRUD operations 

---

app/(dashboard)/manage/checkin/page.tsx
app/(dashboard)/page.tsx
components/checkin/CheckInPage.tsx
components/checkin/table/LoginLogTable.tsx
components/checkin/table/columns.tsx
services/customer.ts
types/login-logs.ts

1. 
- Created check in page
- Created check in page component 
- Added to Customers service 
2.
- Changed check in page 
- Added login log table
- Added table columns 
- Added login logs types 
3.
- Changed Check In Page
4.
- Changed dashboard page
---
1.
- Created check-in page: Adds a dedicated dashboard location for scanning users and displaying membership details, aligning with other admin tools.
- Created check-in page component: Encapsulates scan handling and display logic in a reusable component, keeping the page structure clean and consistent.
- Added to customers service: Introduces an API helper that retrieves a user’s membership info, enabling the check-in feature to show up-to-date data.
2.
- Changed check-in page – to capture each successful check-in as a login log and pass …

[Feature] Set up QR scanner so people can scan in at the facility 

---

app/api/docs/square-swagger.json
app/api/square/Api.ts

- Added new swagger doc
---
- Added this file for new endpoints 
---

[Chore] Updated swagger files and auto generated api typescript file 

---

app/(dashboard)/page.tsx
utils/checkinLogs.ts

- Changed dashboard page 
- Changed login util 
---
- Changed dashboard page: The dashboard page was updated to replace the hard-coded check-in count with a live counter that updates in real time, reflecting each new check-in as it happens.
- Changed login util: The log utility was revised to retain check-in records for 48 hours while resetting the counter every 24–25 hours, ensuring accurate daily tracking for the dashboard display.
---
---
- https://trello.com/c/hMQUAIxI/314-add-check-in-counter-on-dashbaord
---

[Feature] Check In counter on Dashboard page 

---

components/todo-list.tsx

- Changed todo list
---
- The todo list was updated to load and save tasks via localStorage so user-added items persist across reloads or token refreshes instead of relying on hard-coded entries
---
---
- https://trello.com/c/0c4y9caz/319-to-do-list-dashboard
---

[Chore] Added functionality for to do list on the dashboard 

---

components/staff/StaffForm.tsx
components/staff/StaffProfilePictureUpload.tsx
components/staff/StaffTable.tsx
components/staff/columnsStaff.tsx
services/staff.ts
services/upload.ts
types/user.ts

- Changed staff form
- Changed staff table
- Changed staff service 
- Created profile picture upload 
- Created upload service 
- Changed user type
- Changed staff column 
---
- Changed staff form - The form now embeds the profile picture uploader and reorganized sections for personal, contact, and role data so admins can edit all staff details, including the new avatar, from a single drawer view.
- Changed staff table - The table was enhanced to render staff photos, support column-visibility toggles, and provide inline action menus so users can see the new imagery while quickly selecting entries to edit.
- Changed staff service - The staff service maps the backend’s photo_url into the User model and exposes a dedicated profile-update call, enabling the UI changes to persist uploaded …

[Feature] Staff / Coach profile pictures

---

app/api/docs/swagger.json
components/customers/CustomerInfoPanel.tsx
components/customers/CustomerTable.tsx
components/customers/CustomersManager.tsx
services/customer.ts
types/customer.ts

Adding Credits to Customer table 
- Changed customer table 
- Changed customer manager 
- Added to customer service 
- Added to customer type 
- Changed customer table: We added a non-sortable Credits column so each row can display the fetched credit balance alongside existing customer details.
- Changed customer manager: The manager now fetches credit balances for both active and archived customers and merges the results into local state so the table has up-to-date values to render.
- Added to customer service: New parsing helpers and a getCustomerCredits call normalize varied API responses from GET admin/customers/{id}/credits into numeric totals the UI can use.
- Added to customer type: The Customer interface now exposes an optional credits field to hold the retrieved balance beside …

[Feature] Credits for Customers

---

components/Barbershop/Appointments.tsx
components/Barbershop/ManageBarberServices.tsx
components/Playground/AddSystemForm.tsx
components/Playground/PlaygroundPage.tsx
components/Playground/SystemsPage.tsx
components/checkin/CheckInPage.tsx
components/courts/AddCourtForm.tsx
components/courts/CourtInfoPanel.tsx
components/courts/CourtPage.tsx
components/customers/CustomerInfoPanel.tsx
components/customers/CustomerPage.tsx
components/customers/infoTabs/CustomerDetails.tsx
components/locations/AddLocationForm.tsx
components/locations/LocationPage.tsx
components/locations/infoTabs/Details.tsx
components/memberships/infoTabs/plans/Plans.tsx
components/programs/ProgramInfoPanel.tsx
components/programs/ProgramPage.tsx
components/programs/infoTabs/Details.tsx
components/staff/StaffForm.tsx
components/staff/StaffPage.tsx
components/teams/AddTeamForm.tsx
components/teams/TeamInfoPanel.tsx
components/teams/TeamsPage.tsx
components/todo-list.tsx
lib/programValidation.ts
utils/inputValidation.ts

- Added regex  for all inputs
---
- Added this so all inputs are sanitized and valid before being sent to the backend for an extra layer of security 
---
---
- https://trello.com/c/vOuipEFO/345-add-regex-to-inputs
---
- One file has lots of formatting changes

[Chore] Added regex for all inputs

---

app/api/Api.ts
components/calendar/CalendarPage.tsx
components/calendar/dialog/calendar-manage-event-drawer.tsx
components/calendar/event/AddEventForm.tsx
components/calendar/event/EditEventForm.tsx
services/events.ts
types/calendar.ts
types/events.ts

- Added Credits to display and choose when adding events
- Added Courts to display on events, practices and games that are on the calendar page 
---
- Added credits so users can create an event that users will pay for with credits 
- Added courts to display on events so users know what court they are on if one has been selected 
---
---
- https://trello.com/c/dVkTZMD8/347-add-credits-for-event-creation
---

[Chore] Add credits to events / fix events courts 
