RISE-sait/Rise-Admin-Shad-Version

app/(dashboard)/manage/customers/page.tsx
components/Barbershop/AddAppointmentForm.tsx
components/Barbershop/Appointments.tsx
components/customers/CustomerPage.tsx
components/customers/CustomerTable.tsx
services/customer.ts

-  Replaced the old prev and next buttons with proper buttons using pagination
- 
- 
---
we need this because the buttons would only display 20 customers without dynamically getting other pages from the API response
now when we click next or prev the api will get called with the corresponding page number. it also shows the total count of customers and what page they are currently on
---
---
---
https://trello.com/c/DYY8WX85/188-display-more-customers-properly-only-displays-20
---

[Feature] Added proper pagination buttons to the customers page

---

services/events.ts

- Updated all GET event-related API calls to use the /secure/events endpoint and include the JWT in the Authorization header.
---
- The /secure/events endpoint requires authentication, so adding the JWT ensures only authorized users can access event data relevant to their role or permissions.
---
---
- https://trello.com/c/TdFp9zNt/193-add-games-and-events-to-have-user-based-views-on-the-admin-panel
---

[Chore] Made GET event endpoints secure

---

components/memberships/infoTabs/plans/Plans.tsx
services/membershipPlan.ts
types/membership.ts

- Added membership Plan service
- Added price and joining fee to membership plan type
- Switched all stripe id relates items to price
---
- Centralizing the API logic with getPlansForMembership provides a single, reusable way to retrieve plan data for any component
- Including price and joining_fee fields in the MembershipPlan interface lets the UI hold actual monetary values rather than only Stripe IDs
- The Plans component now formats and displays each plan’s price instead of showing the stripe_price_id, making the costs clear to users
---
---
---
- https://trello.com/c/DXIZOXGf/176-fix-memberships-so-in-plans-it-shows-price-and-not-id
---
- I think we will need to add joining fee to the backend

[Chore] Fixed membership plans so it shows price instead of stripe id

---

components/staff/StaffForm.tsx
components/staff/StaffPage.tsx
services/staff.ts
services/user.ts

- Changed Staff Form
- Changed Staff Page
- Changed staff services 
- Added User services
---
- Changed Staff Form – The form now includes editable fields for personal details and calls new update helpers so staff data can be saved in one place using the drawer UI.
- Changed Staff Page – The page uses the RightDrawer component to open a consistent side drawer for editing, matching how customer records are modified.
- Changed staff services – A new updateStaff function was added to handle PUT requests to /staffs/{id}, enabling updates to role and active status via the staff API.
- Added User services – A dedicated updateUser service sends the rest of the staff profile fields to the /users endpoint, separating account updates from role and status changes.
---
---
- …

[Chore] Made staff editable in info panel / drawer 

---

components/teams/AddTeamForm.tsx
services/teams.ts

- Changed teams service
- Changed add team form
---
- Changed teams service: The createTeam function was updated to safely handle empty JSON responses so that team creation doesn’t crash with a SyntaxError when the API body is empty.
- Changed add team form: The form now fetches available coaches and provides a dropdown for selection, replacing the free‑text input to avoid invalid coach IDs.
---
---
- https://trello.com/c/B7fe7jFe/220-add-coaches-select-when-adding-a-team
---

[Chore] Fix adding a team. Coach select instead of entering ID 

---

services/teams.ts

- Changed responseJSON 
---
- The deletion API sometimes returns a 204 No Content response, so deleteTeam now reads the body as text and only parses it when content exists, preventing response.json() from throwing a syntax error when the body is empty
---
---
- https://trello.com/c/pUxXi4rF/211-fix-error-when-deleting-team
---

[Chore] Fixed team DELETE error

---

services/teams.ts

- Changed updateTeam JSON response
---
- The change to updateTeam ensures that empty server responses no longer cause a JSON parsing error, preventing the “Unexpected end of JSON input” exception that occurred when editing a team
---
---
- https://trello.com/c/8U6WiycI/210-fix-errors-when-edit-team
---

[Chore] Changed updateTeam to prevent JSON parsing errors

---

components/practices/PracticeInfoPanel.tsx
components/practices/table/columns.tsx
services/practices.ts
types/practice.ts

- Changed Practice info panel 
- Changed table columns 
- Added to practice service and type 
---
- Added a paragraph to conditionally display practice.booked_by, letting users see who booked the practice session in the info panel
- Inserted a “Booked By” column so the practices table lists which coach booked each practice
- The service now sends an auth header and parses the booking coach from the API, while the Practice type includes a booked_by field so this data can be stored and shown
---
---
- https://trello.com/c/0K7QTsa4/233-add-a-booked-by-column-to-practice-table
---

[Feature] Practice table now shows who booked the practice based on User

---

actions/serverActions.ts
app/(dashboard)/manage/facilities/page.tsx
components/app-sidebar.tsx

- Added to server actions
- Created new facilities page
- Changed sidebar
---
- Added to server actions - The project now revalidates /manage/facilities whenever locations or courts change so the combined Facilities page stays up‑to‑date
- Created new facilities page - A new server component fetches both locations and courts, merges location names into court data, and renders the existing Locations and Courts components together on one page
- Changed sidebar - The sidebar navigation entry formerly titled “Locations” now reads “Facilities” and points to /manage/facilities for direct access to the combined view
---
---
---
- https://trello.com/c/hbDJN1kN/237-merge-locations-and-courts-page
---

[Chore] Merge Location and Court Pages into new Facilities Page

---

app/(dashboard)/manage/amenities/page.tsx
components/app-sidebar.tsx

- Added amenities page
- Changed sidebar 
---
- Added amenities page - This new page consolidates the barbershop and playground content under one route, so admins can manage both amenities in a single place instead of navigating to separate pages
- Changed sidebar - The sidebar now links directly to the new “Amenities” page (and no longer shows separate Barbershop or Playground items) to keep navigation consistent with the page merge
---
---
- https://trello.com/c/VjdtGmUw/239-merge-playground-and-barber-shop-into-amenties-using-column-layout
---

[Chore] Merged Barbershop and Playground into Amenities

---

components/calendar/dialog/calendar-manage-event-drawer.tsx
services/events.ts

- Changed event drawer
- Added Delete to events service 
---
- Changed event drawer - Updated the calendar manage event drawer so that deleting an event calls the new API helper, shows success or error toasts, and refreshes the event list for accurate UI updates.
- Added Delete to events service - Introduced a deleteEvent helper in services/events.ts that makes an authenticated DELETE request to the /events endpoint, allowing events to be removed on the server.
---
---
- https://trello.com/c/eETj5UrQ/250-delete-event-on-calendar-page
---

[Chore] Added delete functionality to the events on the calendar page

---

app/layout.tsx
components/TokenRefresher.tsx

- Created Token refresher component 
- Added token refresher to root layout
---
- A new TokenRefresher periodically calls Firebase to refresh the JWT every ten minutes, updating both local storage and user context so tokens don’t expire during long sessions
- Importing and rendering TokenRefresher inside the RootLayout ensures this background refresh runs for all pages, keeping tokens valid whenever the app is open
---
---
- https://trello.com/c/fjxLHCLg/252-add-jwt-refresher-component
---

[Feature] Added JWT refresher component 

---

app/(dashboard)/manage/customers/page.tsx
components/customers/CustomerInfoPanel.tsx
components/customers/CustomerPage.tsx
components/customers/CustomersManager.tsx

- Changed customer page
- Changed customer info panel 
- Changed Customer page component 
- Created customers manager component
---
- Changed customer page - The dashboard page now renders a CustomersManager component instead of two separate CustomerPage components so that active and archived lists stay synchronized without reloading the page
- Changed customer info panel - CustomerInfoPanel updates its local state and shows toast messages when a customer is archived or unarchived, and passes the updated data back through its callback for immediate UI refresh
- Changed Customer page component - CustomerPage keeps a local customerList and updates it when customers are edited, archived, or unarchived, closing the drawer and displaying success toasts so the table reflects changes instantly
- …

[Chore] Fixed Customers page so it will refresh automatically after CRUD operations 

---

components/customers/CustomerInfoPanel.tsx
components/customers/CustomerTable.tsx

- Changed customer info panel
- Changed customer table 
---
- Changed customer info panel / Changed customer table - Added an AlertDialog around the archive button so the user must confirm before archiving or unarchiving a customer, preventing accidental actions 
---
---
- https://trello.com/c/FMxxgrOE/257-add-styles-to-customers-confirm-archive-unarchive
---

[Chore] Added Alert styling on confirms for archiving and unarchiving customers 

---

components/locations/LocationInfoPanel.tsx
components/locations/LocationPage.tsx
components/locations/infoTabs/Details.tsx

- Changed location info panel
- Changed location page
- Changed info tabs details 
---
- Location Info Panel - The panel now accepts an optional onDelete callback and forwards it to the DetailsTab so the parent drawer can be closed after a location is removed
- Location Page - A new handleDrawerClose function closes the drawer and clears the selected facility, and this function is supplied both to RightDrawer and to FacilityInfoPanel so that deleting a location or manually closing the drawer leaves the page in a clean state
- Details tab - The Details tab imports the shared AlertDialog components, supports an optional onDelete prop, and replaces the browser confirm dialog with this alert so deletion is confirmed once and triggers the provided callback after a successful API call
---
---
- …

[Chore] Added alert components to match styling of deletes across the app on the locations components 

---

components/staff/StaffForm.tsx
components/staff/StaffPage.tsx

- Changed staff form
- Changed staff page component 
---
- Changed staff form: To replace the native browser confirm with the event-style AlertDialog and ensure the drawer closes automatically after a staff member is deleted.
- Changed staff page component: To pass the drawer’s close handler into the form so deleting a staff member closes the info panel without additional user interaction.
---
---
- https://trello.com/c/xEmVJYrP/263-add-styles-to-staff-confirm-delete
---

[Chore] Added styles to confirm delete alert

---

components/teams/TeamInfoPanel.tsx

- Changed team info panel
---
- TeamInfoPanel was updated to use the shared AlertDialog instead of the native confirm prompt, ensuring consistent deletion confirmation without duplicate prompts or missing toast notifications.
---
---
- https://trello.com/c/dZXbM1WL/264-add-styles-to-teams-confirm-delete
---

[Chore] Added alert styling to confirm delete for teams

---

components/practices/PracticeInfoPanel.tsx

- Changed practice info panel 
---
- We needed this change to replace the inconsistent browser confirm with a unified ShadCN alert dialog for deleting practices, ensuring a consistent and single confirmation flow across the app.
---
---
- https://trello.com/c/RYNusv9h/265-add-styles-to-practice-confirm-delete
---

[Chore] Added alert styling to confirm deletes for practices 

---

components/teams/TeamInfoPanel.tsx

- Changed team info panel 
---
- The TeamInfoPanel was updated so the current roster and player count are immediately visible, empty rosters display a clear message, and the Manage Roster button stands out for first-time users.
---
---
- https://trello.com/c/Hr7ugiug/274-style-the-roster-addition
---

[Chore] Restyled the roster section

---

components/calendar/body/month/calendar-body-month.tsx
components/calendar/event/calendar-event.tsx

- Changed calendar event component
- Changed calendar body month component
---
- Changed calendar event component – Introduced day-aware layout keys so Framer Motion treats each day of a multi-day event as distinct, preventing layout collisions.
- Changed calendar body month component – Passed a day-specific key and current date to each event instance so multi-day events render across every day they span.
---
---
- https://trello.com/c/IlLrUI7f/275-fix-multi-day-events-so-they-always-show-up
---

[Bugfix] Multi day events will now show up and display across all days they are scheduled on 

---

components/Playground/BookingInfoPanel.tsx

- Changed booking info panel so it has styled alerts for canceling a session 
---
- The change replaces the default browser confirm with an app-wide alert dialog labeled “Cancel” to match the rest of the UI and maintain consistent terminology and user experience.
---
---
- https://trello.com/c/9LfyZoXf/267-add-styles-to-playground-confirm-cancel
---

[Chore] Added styling on Cancel Confirmation on playground page

---

components/Barbershop/AppointmentInfoPanel.tsx
components/Barbershop/Appointments.tsx
components/Barbershop/BarberTable.tsx

- Changed appointment info panel 
- Changed appointments 
- Changed barber table
---
- Changed appointment info panel – replaced the default browser confirm with a styled alert dialog so users cancel appointments through a consistent, branded UI.
- Changed appointments – updated list view actions to use “Cancel Appointment” phrasing and the new cancellation dialog to align with the rest of the app’s toast-driven workflow.
- Changed barber table – rewired table actions to trigger the same cancellation dialog and toast messages, ensuring unified behavior across all barbershop scheduling components.
---
---
- https://trello.com/c/tO71f27X/268-add-styles-to-barbershop-confirm-cancel
---

[Chore] Added alerts for confirming a cancelation of a Barbershop Appointment 

---

components/games/GameInfoPanel.tsx

- Changed Game info panel 
---
- It was needed to replace the browser’s default confirm dialog with the app’s custom alert dialog so game deletions follow the same confirmation style used elsewhere in the interface.
---
---
- https://trello.com/c/Q7dgf3GP/279-add-styles-to-confirming-delete-games
---

[Chore] Added alert styling when confirming a delete of a game

---

lib/dates.ts
services/events.ts

- Changed events service
- Changed dates lib
---
- Changed events service: The event service now uses parseEventDate when mapping schedule and event times, ensuring backend strings like "YYYY-MM-DD HH:MM:SS -0600" are converted into accurate Date objects instead of shifting by six hours
- Changed dates lib: A new parseEventDate utility sanitizes backend date strings by removing duplicate timezone offsets and translating several format variants into standard ISO strings, preventing misinterpretation of America/Edmonton timestamps as UTC
---
---
- https://trello.com/c/p8lfSQXB/273-fix-reoccurring-events
---

[Bugfix] Using Parse event data from website to fix 6 hour time difference on AP

---

components/calendar/event/EditEventForm.tsx
components/games/GameInfoPanel.tsx
components/practices/PracticeInfoPanel.tsx
lib/utils.ts

- Added to utils lib file
- Changed edit event form
- Changed Game info panel
- Changed practice info panel 
---
- Added to utils lib file: Introduced timezone-aware helpers like toLocalISOString and neutral offset handling to convert stored timestamps without shifting local times.
- Changed edit event form: Replaced direct ISO formatting with the new local-time helper so events open in the editor at the correct hour instead of appearing six hours off.
- Changed Game info panel: Updated all game-related datetime fields to use the local formatting helper, preventing inadvertent timezone shifts when displaying or editing game times.
- Changed practice info panel: Adopted the same local-time utilities for practice events, ensuring practice times remain accurate during viewing and updates. …

[Bugfix] Edit time now shows correct time instead of six hours different 

---

components/locations/AddLocationForm.tsx
components/locations/LocationPage.tsx

- Changed add location form
- Changed Location page 
---
- Changed add location form – to expose an onSuccess callback so the parent can react (e.g., close the drawer) immediately after a facility is successfully created.
- Changed Location page – to pass the drawer’s close handler via that callback, ensuring the side panel closes automatically once a facility is added for better UX.
---
---
- https://trello.com/c/wWXVTY2D/289-create-location-auto-close-side-panel
---

[Chore] Added auto closer for after adding a location

---

components/courts/AddCourtForm.tsx
components/courts/CourtPage.tsx

- Changed add court form
- Changed court page 
---
- Changed add court form: Introduced an optional post-add callback so the drawer could close automatically after a successful court creation.
- Changed court page: Passed the drawer’s close handler into the form so the side panel shuts when a new court is added.
---
---
- https://trello.com/c/AbxsE5YZ/290-create-court-auto-close-side-panel
---

[Chore] Added a auto closer after adding a new court

---

components/courts/CourtInfoPanel.tsx
components/customers/CustomerInfoPanel.tsx
components/customers/CustomerPage.tsx
components/customers/infoTabs/CustomerDetails.tsx
components/games/GameInfoPanel.tsx
components/locations/LocationInfoPanel.tsx
components/locations/LocationPage.tsx
components/locations/infoTabs/Details.tsx
components/practices/PracticeInfoPanel.tsx
components/programs/ProgramInfoPanel.tsx
components/staff/StaffForm.tsx
components/teams/TeamInfoPanel.tsx

- Added auto closers to Locations, Courts, Memberships, Staff, Teams, Games, Practices, Customers, Archived Customers and Programs 
---
- The changes were necessary to improve user experience: previously, after updating entities like programs or courts, the info drawer remained open, leaving the interface in an inconsistent state. By invoking each panel’s onClose callback after a successful save, the drawer closes automatically, revealing the updated list view and ensuring the UI reflects the new data immediately
---
---
- https://trello.com/c/b1I5bn0D/302-auto-close-after-updating
---

[Chore] Added auto closers after updating anything on the AP

---

components/teams/RosterEditor.tsx
components/teams/TeamInfoPanel.tsx

- Changed Roster Editor 
- Changed Team info Panel 
- Updated Styling on the roster editor 
---
- Changed Roster Editor - Added an optional onRosterChange callback that gets invoked when closing the editor so parent components can refresh the roster immediately
- Changed Team Info Panel - Tracks the roster in local state and passes setRoster to the editor’s onRosterChange prop, letting the panel display roster edits in real time without a manual refresh
- Updated Styling on the roster editor - Added the save icon and changed the color to green so the save button matches the styling across the app and keeps it consistent 
---
---
- https://trello.com/c/IjkanB8T/308-add-auto-update-so-roster-changes-are-visualized-right-away
---

[Chore] Added Roster update functions with styling

---

components/memberships/infoTabs/plans/Plans.tsx
services/membershipPlan.ts

- Changed membership plan info tab
- Changed membership plan service 
---
- Membership plan info tab - A formatPrice helper now formats each plan’s price before render, ensuring the header always shows a valid CAD amount instead of “CA$NaN”
- Membership plan service - A parseNumber utility sanitizes API price fields into numbers, preventing “NaN” values when formatting plan price and joining fee
---
---
- https://trello.com/c/DDFM5Y9l/286-fix-displaying-membership-plan-price
---

[Chore] Fix Membership Plan Price display 

---

components/practices/AddPracticeForm.tsx
components/practices/PracticeInfoPanel.tsx
components/practices/table/columns.tsx
types/practice.ts

- Changed add practice form
- Changed practice info panel 
- Changed practice table 
- Changed practice type 
---
- Changed add practice form: The form was updated so users can create practices without selecting a court, reflecting that a court is now optional.
- Changed practice info panel: The panel now conditionally shows and submits court information only when present, ensuring edits respect optional court assignments.
- Changed practice table: A placeholder dash is displayed when a practice lacks a court, clearly indicating unassigned court entries in the table.
- Changed practice type: The practice request types were modified to make the court ID optional so backend calls accept practices without a court.
---
---
- https://trello.com/c/QICg4gQC/315-make-court-optional-for-practice …

[Chore] Made courts optional for booking a practice

---

components/calendar/body/month/calendar-body-month.tsx
components/calendar/body/week/calendar-body-week.tsx

- Changed body month and week
---
- The calendar previously calculated weeks starting on Monday, causing the weekly and monthly views to misalign with users in regions (like the U.S.) where weeks begin on Sunday. By anchoring both views to Sunday, the displayed dates and weekday headers now align with a Sunday‑first convention, eliminating mismatches.
---
---
- https://trello.com/c/cclgbjyX/316-change-calendar-so-sunday-is-first
---

[Chore] Changed first day of the week to Sunday

---

components/calendar/dialog/calendar-manage-event-drawer.tsx
components/calendar/event/EventStaffTab.tsx
services/events.ts
types/events.ts

- Changed manage event drawer 
- Created Event staff tab
- Changed event service
- Changed event type
---
- Changed manage event drawer: The manage-event drawer now wraps its content in a Details/Staff tab set and syncs state updates from staff edits so users can access the new staffing workflow without losing the existing event view.
- Created Event staff tab: The new EventStaffTab component handles loading, searching, and optimistically assigning or removing staff with toast feedback and calendar revalidation, giving the UI a dedicated place to manage event staffing.
- Changed event service: The events service gained assign/unassign helpers and richer single-event parsing so the frontend can call the staff assignment endpoints and receive the staff list in event responses.
- Changed …

[Feature] Staff enrolment for events

---

components/memberships/infoTabs/plans/Plans.tsx
services/membershipPlan.ts
types/membership.ts

- Changed membership info tabs
- Changed membership plan service 
- Changed membership type
---
- The membership info tab needed to capture Stripe price/join IDs and optional credit settings directly in the UI state so labels, summaries, and POST/PUT payloads reflect the identifiers and only include credit data when the “Using credits” controls are active.
- The membership plan service needed to forward the backend’s Stripe and credit fields verbatim instead of synthesizing price values, ensuring clients receive the exact identifiers and optional credit metadata returned by the API.
- The shared membership types had to expose optional credit allocation and weekly limit fields (while centering on Stripe identifiers) so downstream consumers can work with the newly surfaced plan data safely. …

[Chore] Fixed membership plan POST / PUT

---

app/(dashboard)/manage/barbershop/availability/page.tsx
app/api/docs/swagger.json
components/Barbershop/AvailabilityForm.tsx
components/Barbershop/BarberPage.tsx
components/Barbershop/ManageBarberAvailability.tsx
services/barberAvailability.ts

- Created barber shop availability page
- Created availability form
- Updated barber page component 
- Created manage barber availability 
- Created barber availability services 
---
- Creating the barber shop availability page wires the dashboard route to the new management component so barbers can reach the availability interface directly from /manage/barbershop/availability.
- Building the AvailabilityForm encapsulates the normalized day-of-week mapping, validation, and consistent save/delete controls required to create and update slots within the drawer workflow.
- Updating the BarberPage navigation adds a shortcut that points barbers to the availability manager alongside existing management links, making the new feature discoverable.
- Implementing ManageBarberAvailability supplies …

[Feature] Added Barber Availability to the Barber page 
